name: "gcp Setup"
description: "Setup gcp client and auth"
inputs:
  service-account-email:
    description: "Service account email for WIF"
    required: true
  workload-identity-provider:
    description: "Workload Identity Provider path (projects/PROJECT_NUMBER/locations/global/workloadIdentityPools/POOL_ID/providers/PROVIDER_ID)"
    required: true
  artifact-registry-endpoint:
    description: "Artifact Registry endpoint"
    required: true

runs:
  using: "composite"
  steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: GCP authentication
      id: auth
      uses: google-github-actions/auth@v2
      with:
        workload_identity_provider: ${{ inputs.workload-identity-provider }}
        service_account: ${{ inputs.service-account-email }}
        token_format: 'access_token'

    - name: Authenticate to Google Artifact Registry
      uses: docker/login-action@v3
      with:
        registry: ${{ inputs.artifact-registry-endpoint }}
        username: oauth2accesstoken
        password: ${{ steps.auth.outputs.access_token }}

    - name: 'Set up Cloud SDK'
      uses: 'google-github-actions/setup-gcloud@v2'
